# Generated by Django 4.2.22 on 2025-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0835_alter_externaldatasource_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertcheck",
            name="raw_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
